language: python
python:
  - 2.7
notifications:
  email: false
env:
  - CPATH=/home/travis/miniconda2/lib/python2.7/site-packages/numpy/core/include
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  #- export PATH=/home/travis/miniconda2/bin:$PATH
  - source /home/travis/miniconda2/bin/activate root
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy nose cython 
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install dendropy
  - conda update pip
  - easy_install --upgrade distribute
  - python setup.py build_ext -i

# Run test
script:
  - nosetests --with-cov --cover-test SuchTree

# Calculate coverage
after_success:
  - coveralls
